import type {KidName,Question,SeenQuestion,SkillMastery,Subject} from '../types'
import {children} from '../data/children'
import {subjectMeta} from '../data/learningCatalog'
import {masterPool} from '../data/questionFactory'
import {hashString,mulberry32,shuffled} from './random'
import {masteryAverage,reviewDueSkills,weakestSkills} from './mastery'
import {sanitizeQuestions} from './validation'
export interface GenerateContext{mastery?:Record<string,SkillMastery>;seen?:SeenQuestion[];difficultyOverride?:'easier'|'normal'|'harder'|'adaptive'}
const COMPOSITE:Subject[]=['DailyReview','WeakSkills','WeeklyReview','MonthlyMastery','DailyChallenge','MasterChallenge']
export function quizCountFor(subject:Subject){return subjectMeta[subject]?.single?1:5}
const dayNumber=()=>Math.floor(Date.now()/86400000)
function seedFor(child:KidName,subject:Subject,quiz:number){const day=dayNumber(),rotation=day%3,cycle=Math.floor(day/3);return hashString(`${child}|${subject}|${quiz}|rotation-${rotation}|cycle-${cycle}|v8`)}
function recentSet(seen:SeenQuestion[]=[]){const cutoff=Date.now()-30*86400000;return new Set(seen.filter(s=>s.seenAt>=cutoff).map(s=>s.id))}
function balanced(pool:Question[],count:number,rnd:()=>number,priority:string[]=[]){const groups=new Map<string,Question[]>();for(const item of pool)groups.set(item.skill,[...(groups.get(item.skill)||[]),item]);let keys=shuffled([...groups.keys()],rnd);if(priority.length)keys=[...priority.filter(k=>groups.has(k)),...keys.filter(k=>!priority.includes(k))];const out:Question[]=[];let cursor=0;while(out.length<count&&keys.length&&cursor<count*120){const key=keys[cursor%keys.length],list=groups.get(key)!;if(list.length)out.push(list.splice(Math.floor(rnd()*list.length),1)[0]);cursor++}return out}
function sourcesFor(child:KidName){return children[child].subjects.filter(s=>!COMPOSITE.includes(s)&&s!=='ReadingFluency')}
function targetDifficulty(quiz:number,mastery:Record<string,SkillMastery>={},override:GenerateContext['difficultyOverride']='adaptive'){const avg=masteryAverage(mastery);let target=quiz===1?(avg>=82?2:avg<45?1:1.5):Math.min(6,quiz+.5+(avg>=88?.35:avg<50?-.35:0));if(override==='easier')target-=.75;if(override==='harder')target+=.75;if(override==='normal')target=quiz===1?1.5:quiz+.25;return Math.max(1,Math.min(6,target))}
function filterDifficulty(pool:Question[],quiz:number,ctx:GenerateContext){const target=targetDifficulty(quiz,ctx.mastery||{},ctx.difficultyOverride),low=Math.max(1,target-1),high=quiz===1?Math.min(2.75,target+.75):Math.min(7,target+1.25),f=pool.filter(q=>q.difficulty>=low&&q.difficulty<=high);return f.length>=20?f:pool}
function compositePool(child:KidName,subject:Subject,quiz:number,ctx:GenerateContext){const out:Question[]=[];for(const s of sourcesFor(child)){const qz=quizCountFor(s)===1?1:Math.max(1,Math.min(5,quiz));out.push(...masterPool(child,s,qz,180).map(x=>({...x,subject})))}if(subject==='WeakSkills'){const weak=weakestSkills(ctx.mastery||{},10).map(w=>w.skill);return out.filter(q=>!weak.length||weak.includes(q.skill))}if(subject==='DailyReview'){const due=reviewDueSkills(ctx.mastery||{},12).map(w=>w.skill),weak=weakestSkills(ctx.mastery||{},5).map(w=>w.skill),targets=[...new Set([...due,...weak])];return targets.length?out.filter(q=>targets.includes(q.skill)):out}return out}
function baseCount(child:KidName,subject:Subject){if(subject==='MasterChallenge')return child==='Faith'||child==='Angel'?40:32;if(subject==='MonthlyMastery')return child==='Faith'||child==='Angel'?45:35;if(subject==='WeeklyReview')return 30;if(subject==='DailyReview')return 15;if(subject==='DailyChallenge')return 1;if(subject==='WeakSkills')return 18;if(subject==='ReadingFluency')return 10;if(['DigitalTime','Science','Geography'].includes(subject))return 20;return children[child].coreQuestions}
function signature(q:Question){return `${q.skill}|${q.prompt.replace(/\d+/g,'#').toLowerCase().slice(0,120)}`}
function avoidNearDuplicates(items:Question[],count:number){const used=new Set<string>(),out:Question[]=[];for(const item of items){const sig=signature(item);if(used.has(sig)&&out.length<count*.7)continue;used.add(sig);out.push(item);if(out.length>=count)break}return out}
export function generateQuiz(child:KidName,subject:Subject,quiz:number,ctx:GenerateContext={}){const rnd=mulberry32(seedFor(child,subject,quiz)),recent=recentSet(ctx.seen),count=baseCount(child,subject);let pool=COMPOSITE.includes(subject)?compositePool(child,subject,quiz,ctx):masterPool(child,subject,quiz,520);pool=filterDifficulty(pool,quiz,ctx);let fresh=pool.filter(q=>!recent.has(q.id));if(fresh.length<count*1.5)fresh=pool;const priority=subject==='WeakSkills'?weakestSkills(ctx.mastery||{},10).map(w=>w.skill):subject==='DailyReview'?reviewDueSkills(ctx.mastery||{},8).map(w=>w.skill):[];let selected:Question[];if(subject==='MasterChallenge'||subject==='MonthlyMastery'){const weak=weakestSkills(ctx.mastery||{},10).map(w=>w.skill),mastered=Object.values(ctx.mastery||{}).filter(m=>m.status==='Mastered'||m.status==='Review Due').map(m=>m.skill),used=new Set<string>(),take=(src:Question[],n:number)=>{const a:Question[]=[];for(const item of src){if(a.length>=n)break;if(!used.has(item.id)){used.add(item.id);a.push(item)}}return a},w=take(shuffled(fresh.filter(q=>weak.includes(q.skill)),rnd),Math.round(count*.28)),m=take(shuffled(fresh.filter(q=>mastered.includes(q.skill)),rnd),Math.round(count*.18)),g=take(shuffled(fresh,rnd),count-w.length-m.length);selected=shuffled([...w,...m,...g],rnd)}else selected=balanced(shuffled([...fresh],rnd),count,rnd,priority);selected=avoidNearDuplicates(selected,count);if(subject==='DailyChallenge')selected=selected.map(x=>({...x,challenge:true,difficulty:Math.min(7,x.difficulty+1),prompt:`⭐ ${x.prompt}`}));return sanitizeQuestions(selected)}
export function remediationQuestion(original:Question,offset:number,ctx:GenerateContext={}){const sources=COMPOSITE.includes(original.subject)?sourcesFor(original.child):[original.subject],all=sources.flatMap(s=>masterPool(original.child,s,Math.max(1,Math.min(5,original.quiz)),300)).filter(q=>q.skill===original.skill&&!recentSet(ctx.seen).has(q.id)&&q.id!==original.id),rnd=mulberry32(hashString(`${original.id}-rem-${offset}-${dayNumber()}`)),next=shuffled(all,rnd)[0]||original;return{...next,id:`REM-${offset}-${next.id}-d${dayNumber()}`,prompt:`Review: ${next.prompt}`}}
