export type StoreCategory='Avatar'|'Accessory'|'Theme'|'Aquarium'|'Cabin'|'Companion'|'Vehicle'|'Effect'|'Frame'
export type Rarity='Common'|'Uncommon'|'Rare'|'Epic'|'Legendary'
export interface StoreItem{id:string;name:string;icon:string;category:StoreCategory;price:number;description:string;value:string;rarity:Rarity}
export const storeItems:StoreItem[]=[
{id:'avatar-orca',name:'Orca Avatar',icon:'🐋',category:'Avatar',price:.35,description:'A bold ocean avatar.',value:'🐋',rarity:'Common'},{id:'avatar-otter',name:'Otter Avatar',icon:'🦦',category:'Avatar',price:.35,description:'A playful explorer.',value:'🦦',rarity:'Common'},{id:'avatar-axolotl',name:'Axolotl Avatar',icon:'🦎',category:'Avatar',price:.45,description:'A rare aquatic friend.',value:'🦎',rarity:'Uncommon'},{id:'avatar-dragon',name:'Sea Dragon Avatar',icon:'🐉',category:'Avatar',price:.85,description:'A legendary-looking explorer avatar.',value:'🐉',rarity:'Rare'},
{id:'acc-crown',name:'Explorer Crown',icon:'👑',category:'Accessory',price:.50,description:'Wear a gold crown around your avatar.',value:'👑',rarity:'Uncommon'},{id:'acc-glasses',name:'Scholar Glasses',icon:'👓',category:'Accessory',price:.40,description:'Smart glasses for study mode.',value:'👓',rarity:'Common'},{id:'acc-pirate',name:'Pirate Hat',icon:'🏴‍☠️',category:'Accessory',price:.60,description:'Perfect for shipwreck exploration.',value:'🏴‍☠️',rarity:'Rare'},{id:'acc-diver',name:'Diver Mask',icon:'🥽',category:'Accessory',price:.55,description:'Ocean Expedition diving gear.',value:'🥽',rarity:'Uncommon'},
{id:'theme-coral',name:'Coral Reef Theme',icon:'🪸',category:'Theme',price:.75,description:'A bright coral profile background.',value:'coral',rarity:'Uncommon'},{id:'theme-deep',name:'Deep Ocean Theme',icon:'🌌',category:'Theme',price:.90,description:'A darker glowing ocean profile background.',value:'deep',rarity:'Rare'},
{id:'fish-dolphin',name:'Dolphin Friend',icon:'🐬',category:'Aquarium',price:.55,description:'Add a dolphin to your aquarium.',value:'🐬',rarity:'Uncommon'},{id:'fish-turtle',name:'Sea Turtle Friend',icon:'🐢',category:'Aquarium',price:.50,description:'Add a turtle to your aquarium.',value:'🐢',rarity:'Common'},{id:'fish-octopus',name:'Octopus Friend',icon:'🐙',category:'Aquarium',price:.65,description:'Add an octopus to your aquarium.',value:'🐙',rarity:'Rare'},{id:'fish-shark',name:'Reef Shark',icon:'🦈',category:'Aquarium',price:.80,description:'Add a reef shark to your aquarium.',value:'🦈',rarity:'Rare'},
{id:'cabin-map',name:'Explorer Wall Map',icon:'🗺️',category:'Cabin',price:.45,description:'Hang an expedition map in your cabin.',value:'🗺️',rarity:'Common'},{id:'cabin-lamp',name:'Deep-Sea Lamp',icon:'🏮',category:'Cabin',price:.55,description:'A glowing cabin lamp.',value:'🏮',rarity:'Uncommon'},{id:'cabin-shells',name:'Shell Display',icon:'🐚',category:'Cabin',price:.35,description:'Display collected shells.',value:'🐚',rarity:'Common'},
{id:'companion-crab',name:'Crab Companion',icon:'🦀',category:'Companion',price:.70,description:'A tiny adventure companion.',value:'🦀',rarity:'Rare'},{id:'companion-jelly',name:'Glow Jelly',icon:'🪼',category:'Companion',price:.75,description:'A glowing exploration companion.',value:'🪼',rarity:'Rare'},
{id:'vehicle-sub',name:'Mini Submarine',icon:'🚤',category:'Vehicle',price:1.25,description:'A cosmetic World 1 explorer vehicle.',value:'🚤',rarity:'Epic'},{id:'effect-bubbles',name:'Bubble Trail',icon:'🫧',category:'Effect',price:.45,description:'Bubbles follow your adventure avatar.',value:'🫧',rarity:'Uncommon'},{id:'effect-stars',name:'Star Trail',icon:'✨',category:'Effect',price:.70,description:'A sparkling trail for major explorers.',value:'✨',rarity:'Rare'},{id:'frame-coral',name:'Coral Profile Frame',icon:'🪸',category:'Frame',price:.50,description:'A coral frame around your profile.',value:'coral-frame',rarity:'Uncommon'},{id:'frame-gold',name:'Golden Explorer Frame',icon:'🏆',category:'Frame',price:1.10,description:'A prestige profile frame.',value:'gold-frame',rarity:'Epic'}]
