import type {KidName,KidProgress,Subject} from '../types'
import {levelFromXP,world1Zones} from '../data/adventure'
export const MAX_ENERGY=12
export function learningEnergy(subject:Subject,passed:boolean){if(subject==='DailyChallenge')return 1;if(subject==='MasterChallenge'||subject==='MonthlyMastery')return passed?4:2;return passed?3:2}
export function applyLearningAdventure(p:KidProgress,subject:Subject,firstCorrect:number,passed:boolean){p.adventure.energy=Math.min(MAX_ENERGY,p.adventure.energy+learningEnergy(subject,passed));p.adventure.pearls+=Math.max(1,Math.floor(firstCorrect/5));p.adventure.shells+=passed?2:1;p.adventure.aquarium.food+=passed?1:0;advanceZoneIfReady(p);p.adventure.missions.forEach(m=>{if(m.completed)return;if(m.kind==='daily'||m.kind==='weekly'){if(m.title==='Daily Training'||m.title==='Weekly Expedition')m.progress+=1;if(m.title==='First-Try Explorer')m.progress+=firstCorrect;if(m.progress>=m.target)m.completed=true}})}
export function spendEnergy(p:KidProgress,amount:number){if(p.adventure.energy<amount)return false;p.adventure.energy-=amount;return true}
export function completeObjective(p:KidProgress,id:string,title:string,kid:KidName,rewardXP=25,rewardPearls=3){if(p.adventure.completedObjectives.includes(id))return false;p.adventure.completedObjectives.push(id);if(id.startsWith('room-')&&!p.adventure.shipwreckRooms.includes(id))p.adventure.shipwreckRooms.push(id);if(id.startsWith('npc-')&&!p.adventure.discoveredNpcs.includes(id))p.adventure.discoveredNpcs.push(id);p.adventure.storyChapter=Math.min(8,Math.max(1,p.adventure.bossesDefeated.length+1));p.adventure.xp+=rewardXP;p.adventure.pearls+=rewardPearls;p.adventure.level=levelFromXP(p.adventure.xp);p.adventure.journal.unshift({id:`journal-${Date.now()}-${id}`,createdAt:Date.now(),title,text:`${kid} completed ${title} in World 1.`,icon:'🧭',kind:'story'});const story=p.adventure.missions.find(m=>m.kind==='story');if(story){story.progress=Math.min(story.target,story.progress+1);story.completed=story.progress>=story.target}advanceZoneIfReady(p);return true}
export function claimMission(p:KidProgress,id:string){const m=p.adventure.missions.find(x=>x.id===id);if(!m||!m.completed||m.claimed)return false;m.claimed=true;p.adventure.xp+=m.rewardXP;p.adventure.pearls+=m.rewardPearls||0;p.adventure.level=levelFromXP(p.adventure.xp);advanceZoneIfReady(p);return true}
export function zoneObjectiveCount(p:KidProgress,zoneId:string){return p.adventure.completedObjectives.filter(id=>id.includes(zoneId)).length}
export function canAttemptBoss(p:KidProgress,zoneId:string){const zone=world1Zones.find(z=>z.id===zoneId);if(!zone?.boss)return false;return zoneObjectiveCount(p,zoneId)>=zone.boss.requiredObjectives&&!p.adventure.bossesDefeated.includes(zoneId)}
export function defeatBoss(p:KidProgress,zoneId:string,kid:KidName){const zone=world1Zones.find(z=>z.id===zoneId);if(!zone?.boss||p.adventure.bossesDefeated.includes(zoneId))return false;p.adventure.bossesDefeated.push(zoneId);p.adventure.xp+=150;p.adventure.pearls+=30;p.adventure.level=levelFromXP(p.adventure.xp);p.adventure.journal.unshift({id:`boss-${Date.now()}-${zoneId}`,createdAt:Date.now(),title:`${zone.boss.name} Conquered`,text:`${kid} completed the ${zone.boss.name} mastery trial.`,icon:zone.boss.icon,kind:'story'});advanceZoneIfReady(p);if(zone.id==='lost-atlantis'){p.adventure.world1Complete=true;if(!p.adventure.cabin.trophies.includes('🔱 Ocean Expedition Champion'))p.adventure.cabin.trophies.push('🔱 Ocean Expedition Champion')}return true}
export function zoneRequiredObjectiveIds(zoneId:string){const zone=world1Zones.find(z=>z.id===zoneId);if(!zone)return[];return[...zone.checkpoints.map((_,i)=>`cp-${zone.id}-${i}`),...zone.npcs.map(n=>`npc-${zone.id}-${n.id}`),...zone.shipwrecks.flatMap(s=>s.rooms.map((_,i)=>`room-${zone.id}-${s.id}-${i}`))]}
export function zoneExplorationComplete(p:KidProgress,zoneId:string){const zone=world1Zones.find(z=>z.id===zoneId);if(!zone)return false;const required=zoneRequiredObjectiveIds(zoneId);return required.every(id=>p.adventure.completedObjectives.includes(id))&&(!zone.boss||p.adventure.bossesDefeated.includes(zone.id))}
export function zoneIndex(zoneId:string){return Math.max(0,world1Zones.findIndex(z=>z.id===zoneId))}
export function zoneUnlocked(p:KidProgress,zoneId:string){const target=world1Zones.findIndex(z=>z.id===zoneId),current=zoneIndex(p.adventure.zoneId);return target>=0&&target<=current}
export function nextZoneRequirement(p:KidProgress){const i=zoneIndex(p.adventure.zoneId),current=world1Zones[i],next=world1Zones[i+1];if(!next)return{complete:true,message:'World 1 expedition complete.'};const missing=zoneRequiredObjectiveIds(current.id).filter(id=>!p.adventure.completedObjectives.includes(id)).length;if(missing>0)return{complete:false,message:`Complete ${missing} more exploration objective${missing===1?'':'s'} in ${current.name}.`};if(current.boss&&!p.adventure.bossesDefeated.includes(current.id))return{complete:false,message:`Conquer the ${current.boss.name} Master Challenge.`};if(p.adventure.level<next.minLevel)return{complete:false,message:`Reach Adventure Level ${next.minLevel} to enter ${next.name}.`};return{complete:false,message:`${next.name} is ready to unlock.`}}
export function advanceZoneIfReady(p:KidProgress){let idx=zoneIndex(p.adventure.zoneId),changed=false;while(idx<world1Zones.length-1){const current=world1Zones[idx],next=world1Zones[idx+1];if(p.adventure.level<next.minLevel||!zoneExplorationComplete(p,current.id))break;idx++;p.adventure.zoneId=next.id;p.adventure.currentCheckpoint=next.checkpoints[0]||next.name;p.adventure.storyChapter=Math.max(p.adventure.storyChapter,next.order);p.adventure.journal.unshift({id:`zone-${Date.now()}-${next.id}`,createdAt:Date.now(),title:`New Region: ${next.name}`,text:`World 1 exploration advanced to ${next.name}.`,icon:next.icon,kind:'story'});changed=true}return changed}
