import type {AttemptResult,MasteryStatus,SkillMastery} from '../types'
const REVIEW=[1,3,7,14,30]
export function statusFor(score:number,nextReviewAt?:number):MasteryStatus{if(nextReviewAt&&Date.now()>=nextReviewAt&&score>=70)return'Review Due';return score>=90?'Mastered':score>=75?'Proficient':score>=45?'Developing':'Learning'}
export function updateSkill(existing:SkillMastery|undefined,r:AttemptResult):SkillMastery{const prev=existing??{skill:r.skill,score:42,attempts:0,firstCorrect:0,lastSeen:0,status:'Learning' as MasteryStatus,successfulSessions:0,reviewStage:0},delta=r.firstAttemptCorrect?8:r.eventuallyCorrect?2:-6,score=Math.max(0,Math.min(100,prev.score+delta)),attempts=prev.attempts+1,firstCorrect=prev.firstCorrect+(r.firstAttemptCorrect?1:0),success=prev.successfulSessions+(r.firstAttemptCorrect?1:0);let stage=prev.reviewStage??0,masteredAt=prev.masteredAt,nextReviewAt=prev.nextReviewAt;if(score>=90&&firstCorrect/attempts>=.78&&success>=3){if(!masteredAt)masteredAt=Date.now();stage=Math.min(REVIEW.length-1,stage+1);nextReviewAt=Date.now()+REVIEW[stage]*86400000}else if(!r.firstAttemptCorrect&&score<85){stage=Math.max(0,stage-1);nextReviewAt=Date.now()+86400000}const avg=r.responseMs?Math.round(((prev.responseMsAverage||r.responseMs)*Math.min(prev.attempts,9)+r.responseMs)/(Math.min(prev.attempts,9)+1)):prev.responseMsAverage;return{...prev,score,attempts,firstCorrect,lastSeen:Date.now(),status:statusFor(score,nextReviewAt),successfulSessions:success,masteredAt,nextReviewAt,reviewStage:stage,responseMsAverage:avg}}
export const masteryAverage=(m:Record<string,SkillMastery>)=>{const v=Object.values(m);return v.length?v.reduce((a,s)=>a+s.score,0)/v.length:42}
export const weakestSkills=(m:Record<string,SkillMastery>,limit=5)=>Object.values(m).sort((a,b)=>a.score-b.score||a.lastSeen-b.lastSeen).slice(0,limit)
export const reviewDueSkills=(m:Record<string,SkillMastery>,limit=12)=>Object.values(m).filter(s=>s.nextReviewAt&&Date.now()>=s.nextReviewAt).sort((a,b)=>(a.nextReviewAt||0)-(b.nextReviewAt||0)).slice(0,limit)
export const masteredCount=(m:Record<string,SkillMastery>)=>Object.values(m).filter(s=>s.status==='Mastered').length
export const almostMastered=(m:Record<string,SkillMastery>,limit=6)=>Object.values(m).filter(s=>s.score>=75&&s.score<90).sort((a,b)=>b.score-a.score).slice(0,limit)
