import type {AppState,KidName,LearningWindow,Subject} from '../types'
import {avatarOptions} from '../data/children'
const KEY='coleman_learning_react_v1';export const WINDOW_MS=12*60*60*1000
function emptyWindow():LearningWindow{return{startedAt:0,earnings:0,subjects:{}}}
export function initialState():AppState{const kid=(avatar:string)=>({bank:0,avatar,records:[],window:emptyWindow()});return{version:1,contrast:'bright',kids:{Humberto:kid(avatarOptions[1]),Harmoni:kid(avatarOptions[3]),Faith:kid(avatarOptions[0]),Angel:kid(avatarOptions[2])}}}
export function loadState():AppState{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);return{...initialState(),...parsed,kids:{...initialState().kids,...parsed.kids}}}const fresh=initialState();const legacyRaw=localStorage.getItem('coleman_kids_allowance_tracker');if(legacyRaw){const legacy=JSON.parse(legacyRaw);(['Humberto','Harmoni','Faith','Angel'] as KidName[]).forEach(k=>{const old=legacy[k];if(!old)return;if(Number.isFinite(Number(old.money)))fresh.kids[k].bank=Number(old.money);if(typeof old.avatar==='string')fresh.kids[k].avatar=old.avatar;const ow=old.allowanceWindow;if(ow&&typeof ow==='object'){fresh.kids[k].window.startedAt=Number(ow.start||0);fresh.kids[k].window.earnings=Number(ow.earnings||0);Object.entries(ow.subjects||{}).forEach(([subject,value]:any)=>{const mapped=subject==='MasterTest'?'MasterChallenge':subject;fresh.kids[k].window.subjects[mapped as Subject]={completedQuizzes:Array.isArray(value?.completed)?value.completed.map(Number):[]}})}});const contrast=localStorage.getItem('coleman_contrast_v5');if(contrast==='dark'||contrast==='bright')fresh.contrast=contrast;const voice=localStorage.getItem('coleman_voice_name_v5');if(voice)fresh.preferredVoice=voice;localStorage.setItem(KEY,JSON.stringify(fresh));return fresh}return fresh}catch{return initialState()}}
export function saveState(state:AppState){localStorage.setItem(KEY,JSON.stringify(state))}
export function resetExpiredWindow(state:AppState,kid:KidName){const next=structuredClone(state),win=next.kids[kid].window;if(win.startedAt&&Date.now()-win.startedAt>=WINDOW_MS)next.kids[kid].window=emptyWindow();return next}
export function ensureWindowStarted(state:AppState,kid:KidName){const next=resetExpiredWindow(state,kid);if(!next.kids[kid].window.startedAt)next.kids[kid].window.startedAt=Date.now();return next}
export function subjectCompleted(state:AppState,kid:KidName,subject:Subject){return state.kids[kid].window.subjects[subject]?.completedQuizzes??[]}
export function remainingWindowMs(state:AppState,kid:KidName){const started=state.kids[kid].window.startedAt;if(!started)return WINDOW_MS;return Math.max(0,WINDOW_MS-(Date.now()-started))}
