import {useEffect,useMemo,useRef,useState} from 'react'
import type {AllowanceRules,AppState,KidName,ParentGoal,Subject} from '../types'
import {children} from '../data/children'
import {englishVoices,primeVoices,speakText} from '../engine/voices'
import {almostMastered,masteredCount,masteryAverage,reviewDueSkills,weakestSkills} from '../engine/mastery'
import {createSnapshot,exportKid,exportState,getSnapshots,storageSizeKB} from '../engine/storage'
import {zoneById} from '../data/adventure'
import VoiceStudio from './VoiceStudio'
const HASH='8fe3b7ecf863b75cd14ccf03a0ab0190eabd7d7c7148b8086e9387510c95b389'
async function sha256(v:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('')}
function download(name:string,text:string){const blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),200)}
function webgl(){try{const c=document.createElement('canvas');return Boolean(c.getContext('webgl2')||c.getContext('webgl'))}catch{return false}}
interface Props{state:AppState;build:string;onClose:()=>void;onDeduct:(kid:KidName,amount:number)=>void;onVoice:(name:string)=>void;onRules:(rules:AllowanceRules)=>void;onGoal:(kid:KidName,goal:ParentGoal)=>void;onNote:(kid:KidName,text:string)=>void;onImport:(text:string)=>void;onDifficulty:(kid:KidName,subject:Subject,value:'easier'|'normal'|'harder'|'adaptive')=>void}
export default function ParentPortal({state,build,onClose,onDeduct,onVoice,onRules,onGoal,onNote,onImport,onDifficulty}:Props){
 const [snapshotTick,setSnapshotTick]=useState(0),[ok,setOk]=useState(false),[password,setPassword]=useState(''),[error,setError]=useState(''),[voiceTick,setVoiceTick]=useState(0),[goalKid,setGoalKid]=useState<KidName>('Harmoni'),[goalText,setGoalText]=useState('Complete today’s reading practice'),[goalReward,setGoalReward]=useState(.25),[goalTarget,setGoalTarget]=useState(1),[goalSubject,setGoalSubject]=useState<Subject|''>(''),[noteKid,setNoteKid]=useState<KidName>('Harmoni'),[noteText,setNoteText]=useState(''),[rules,setRules]=useState(state.allowanceRules),[range,setRange]=useState<'window'|'7d'|'30d'|'all'>('window'),[diffKid,setDiffKid]=useState<KidName>('Harmoni'),[diffSubject,setDiffSubject]=useState<Subject>('Math'),[diff,setDiff]=useState<'easier'|'normal'|'harder'|'adaptive'>('adaptive')
 const fileRef=useRef<HTMLInputElement|null>(null)
 useEffect(()=>primeVoices(()=>setVoiceTick(v=>v+1)),[]);useEffect(()=>setRules(state.allowanceRules),[state.allowanceRules]);useEffect(()=>{if(!ok)return;const t=setTimeout(()=>{setOk(false);setPassword('')},state.parentSettings.sessionTimeoutMinutes*60*1000);return()=>clearTimeout(t)},[ok,state.parentSettings.sessionTimeoutMinutes]);const voices=useMemo(()=>englishVoices(),[voiceTick])
 const backupDue=!state.parentSettings.lastBackupAt||Date.now()-state.parentSettings.lastBackupAt>state.parentSettings.backupReminderDays*86400000
 if(!ok)return <main className="parent-shell"><section className="admin-login animated-rise"><div className="admin-lock">🔐</div><h1>Dad & Maggie Parent Admin</h1><p>Enter the family admin password.</p><input type="password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void sha256(password).then(h=>h===HASH?setOk(true):setError('Incorrect password'))}} placeholder="Password"/><button className="primary" onClick={async()=>{if(await sha256(password)===HASH){setOk(true);setError('')}else setError('Incorrect password')}}>Open Portal</button>{error&&<p className="error">{error}</p>}<button className="secondary" onClick={onClose}>Back</button></section></main>
 return <main className="parent-shell"><header className="page-header"><button className="secondary" onClick={onClose}>Close</button><div><h1>Parent Command Center</h1><p>Dad & Maggie controls · device-local GitHub Pages edition</p></div><div className="version-panel"><strong>v{build}</strong><span>Question bank v11</span><span>Storage schema v4</span></div></header>
 {backupDue&&<section className="backup-reminder">💾 Family backup reminder: export a current backup before major updates or device changes.</section>}
 <section className="admin-controls admin-section"><h2>🔊 Voice & iPad Audio</h2><div className="voice-control"><label>Voice on this device<select value={state.preferredVoice||''} onChange={e=>onVoice(e.target.value)}><option value="">Automatic best available voice</option>{voices.map(v=><option key={`${v.name}-${v.lang}`} value={v.name}>{v.name} · {v.lang}{v.localService?' · On device':''}</option>)}</select></label><button className="secondary" onClick={()=>speakText('Hi! This is the voice I will use during the Coleman Family Learning Program.',state.preferredVoice,.88)}>🔊 Test Voice</button></div><div className="voice-help"><strong>Best iPad setup:</strong><ol><li>Settings → Accessibility → Read & Speak → Voices.</li><li>Choose English.</li><li>Download an Enhanced or Premium voice when iPadOS offers one.</li><li>Reload Coleman Learning and test that voice here.</li></ol><p>Dynamic questions still depend on Safari’s speech engine. Use Parent Voice Studio below for natural recurring feedback.</p></div><VoiceStudio/></section>
 <section className="admin-controls admin-section"><h2>💵 Allowance Rules</h2><div className="rules-grid"><label>First-try reward<input type="number" step="0.01" min="0" value={rules.basePerFirstCorrect} onChange={e=>setRules({...rules,basePerFirstCorrect:Number(e.target.value)})}/></label><label>Passing accuracy<input type="number" step="0.05" min="0.5" max="1" value={rules.passThreshold} onChange={e=>setRules({...rules,passThreshold:Number(e.target.value)})}/></label><label>Streak interval<input type="number" min="2" max="10" value={rules.streakEvery} onChange={e=>setRules({...rules,streakEvery:Number(e.target.value)})}/></label><label>Base streak bonus<input type="number" step="0.01" min="0" value={rules.streakBonus} onChange={e=>setRules({...rules,streakBonus:Number(e.target.value)})}/></label><label>Max streak tier<input type="number" min="1" max="10" value={rules.maxStreakTier} onChange={e=>setRules({...rules,maxStreakTier:Number(e.target.value)})}/></label><label>Suggested incorrect deduction<input type="number" step="0.01" min="0" value={rules.incorrectDeduction} onChange={e=>setRules({...rules,incorrectDeduction:Number(e.target.value)})}/></label><label>Challenge bonus<input type="number" step="0.01" min="0" value={rules.challengeBonus} onChange={e=>setRules({...rules,challengeBonus:Number(e.target.value)})}/></label><label>Progressive streak<input type="checkbox" checked={rules.progressiveStreak} onChange={e=>setRules({...rules,progressiveStreak:e.target.checked})}/></label></div><button className="primary" onClick={()=>onRules(rules)}>Save Allowance Rules</button></section>
 <section className="admin-controls admin-section"><h2>🎚️ Difficulty Override</h2><p>Adaptive is recommended. Quiz 1 remains capped as review even when a harder override is selected.</p><div className="goal-form"><select value={diffKid} onChange={e=>{const k=e.target.value as KidName;setDiffKid(k);setDiffSubject(children[k].subjects[0])}}>{Object.keys(children).map(k=><option key={k}>{k}</option>)}</select><select value={diffSubject} onChange={e=>setDiffSubject(e.target.value as Subject)}>{children[diffKid].subjects.map(s=><option key={s}>{s}</option>)}</select><select value={diff} onChange={e=>setDiff(e.target.value as typeof diff)}><option value="adaptive">Adaptive</option><option value="easier">Easier</option><option value="normal">Normal</option><option value="harder">Harder</option></select><button className="primary" onClick={()=>onDifficulty(diffKid,diffSubject,diff)}>Apply</button></div></section>
 <section className="admin-controls admin-section"><h2>🎯 Parent-Assigned Goals</h2><div className="goal-form goal-form-wide"><select value={goalKid} onChange={e=>{const k=e.target.value as KidName;setGoalKid(k);setGoalSubject('')}}>{Object.keys(children).map(k=><option key={k}>{k}</option>)}</select><select value={goalSubject} onChange={e=>setGoalSubject(e.target.value as Subject|'')}><option value="">Any subject</option>{children[goalKid].subjects.map(s=><option key={s} value={s}>{s}</option>)}</select><input value={goalText} onChange={e=>setGoalText(e.target.value)} placeholder="Goal"/><label>Completions<input type="number" min="1" max="20" value={goalTarget} onChange={e=>setGoalTarget(Math.max(1,Number(e.target.value)))}/></label><label>Bonus $<input type="number" step=".05" min="0" value={goalReward} onChange={e=>setGoalReward(Number(e.target.value))}/></label><button className="primary" onClick={()=>{if(!goalText.trim())return;onGoal(goalKid,{id:`goal-${Date.now()}`,text:goalText.trim(),subject:goalSubject||undefined,target:goalTarget,progress:0,reward:goalReward,active:true,createdAt:Date.now()})}}>Assign Goal</button></div></section>
 <section className="admin-controls admin-section"><h2>💬 Parent Notes</h2><div className="goal-form"><select value={noteKid} onChange={e=>setNoteKid(e.target.value as KidName)}>{Object.keys(children).map(k=><option key={k}>{k}</option>)}</select><input value={noteText} onChange={e=>setNoteText(e.target.value)} placeholder="Message for your learner"/><button className="primary" onClick={()=>{if(noteText.trim()){onNote(noteKid,noteText.trim());setNoteText('')}}}>Save Note</button></div></section>
 <section className="admin-controls admin-section"><h2>💾 Backup, Restore & Device Transfer</h2><p>Progress is stored on each device. Backups are the GitHub-only method for preserving and transferring learning history.</p><div className="backup-actions"><button className="primary" onClick={()=>download(`coleman-family-${new Date().toISOString().slice(0,10)}.json`,exportState(state))}>⬇️ Export Family Backup</button>{(Object.keys(children) as KidName[]).map(k=><button className="secondary" key={k} onClick={()=>download(`${k.toLowerCase()}-learning-backup.json`,exportKid(state,k))}>⬇️ {k}</button>)}<button className="secondary" onClick={()=>fileRef.current?.click()}>⬆️ Import Family Backup</button><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={async e=>{const f=e.target.files?.[0];if(f)onImport(await f.text())}}/><button className="secondary" onClick={()=>window.print()}>🖨️ Print Family Report</button></div></section>
 <section className="admin-controls admin-section"><h2>🗄️ Local Save Slots</h2><p>Create up to five device-local restore points before large updates or testing sessions.</p><div className="backup-actions"><button className="primary" onClick={()=>{createSnapshot(state,`Manual Save ${new Date().toLocaleString()}`);setSnapshotTick(v=>v+1)}}>Create Save Snapshot</button></div><div className="snapshot-list" data-refresh={snapshotTick}>{getSnapshots().map(s=><div key={s.id}><span><strong>{s.label}</strong><small>{new Date(s.createdAt).toLocaleString()}</small></span><button className="secondary" onClick={()=>onImport(JSON.stringify(s.state))}>Restore</button></div>)}</div></section><section className="admin-controls admin-section"><h2>🆕 What's New in v{build}</h2><ul className="whats-new"><li>World 1 now includes deeper shipwreck-room exploration and mastery-trial bosses connected directly to the learning engine.</li><li>The Mastery Constellation turns academic skills into an interactive skill tree with Review Due and Mastered states.</li><li>Offline-ready service-worker caching, five local save snapshots, family achievements, and daily/weekly mission refresh improve reliability and long-term progression.</li><li>Worlds 2–10 remain locked placeholders. No future-world content is active.</li><li>Three-day curriculum cycles now combine with 30-day repeat protection and adaptive question generation.</li><li>Spaced review, review-due mastery, weak-skill practice, Weekly Review, Monthly Mastery, and broader grade-adjusted subject banks.</li><li>Improved anti-tapping, misconception hints, delayed remediation, response-time tracking, and mastery prerequisites.</li><li>Parent Voice Studio, backup/export tools, diagnostics, configurable allowance and difficulty, and device transfer.</li></ul></section>
 <section className="admin-controls admin-section diagnostics"><h2>🧪 Diagnostics</h2><div className="diagnostic-grid"><span>Browser<strong>{navigator.userAgent.includes('Safari')&&!navigator.userAgent.includes('Chrome')?'Safari':'Chromium/Other'}</strong></span><span>English voices<strong>{voices.length}</strong></span><span>WebGL<strong>{webgl()?'Available':'Unavailable'}</strong></span><span>Phaser<strong>Bundled v11</strong></span><span>Offline cache<strong>{'serviceWorker' in navigator?'Supported':'Unavailable'}</strong></span><span>Save slots<strong>{getSnapshots().length}/5</strong></span><span>Secure context<strong>{window.isSecureContext?'Yes':'No'}</strong></span><span>Storage<strong>{storageSizeKB()} KB</strong></span><span>Screen<strong>{window.innerWidth}×{window.innerHeight}</strong></span><span>Build<strong>{build}</strong></span></div></section>
 <section className="admin-controls admin-section analytics-range"><h2>📈 Learning Report Range</h2><div className="store-tabs">{(['window','7d','30d','all'] as const).map(r=><button className={range===r?'active':''} key={r} onClick={()=>setRange(r)}>{r==='window'?'Current Window':r==='7d'?'7 Days':r==='30d'?'30 Days':'All Time'}</button>)}</div></section>
 <section className="admin-kids">{(Object.keys(children) as KidName[]).map((kid,idx)=>{const p=state.kids[kid],cutoff=range==='window'?(p.window.startedAt||0):range==='7d'?Date.now()-7*86400000:range==='30d'?Date.now()-30*86400000:0,wr=p.records.filter(r=>r.completedAt>=cutoff),incorrect=wr.reduce((a,r)=>a+r.incorrectFirstAttempts,0),suggested=Number((incorrect*state.allowanceRules.incorrectDeduction).toFixed(2)),weak=weakestSkills(p.mastery,3),zone=zoneById(p.adventure.zoneId),avg=wr.length?wr.reduce((a,r)=>a+r.firstAttemptAccuracy,0)/wr.length:0;return <article className="admin-card animated-rise printable" style={{animationDelay:`${idx*80}ms`}} key={kid}><h2>{p.avatar} {kid}</h2><div className="admin-stats"><span>Window earnings<strong>${p.window.earnings.toFixed(2)}</strong></span><span>Total bank<strong>${p.bank.toFixed(2)}</strong></span><span>Range accuracy<strong>{Math.round(avg*100)}%</strong></span><span>Mastery<strong>{Math.round(masteryAverage(p.mastery))}%</strong></span><span>Mastered skills<strong>{masteredCount(p.mastery)}</strong></span><span>Review due<strong>{reviewDueSkills(p.mastery).length}</strong></span><span>Almost mastered<strong>{almostMastered(p.mastery).length}</strong></span><span>Adventure Level<strong>{p.adventure.level}</strong></span><span>World 1 area<strong>{zone.icon} {zone.name}</strong></span><span>Incorrect first attempts<strong>{incorrect}</strong></span></div><div className="weak-list"><strong>Current focus:</strong>{weak.length?weak.map(w=><span key={w.skill}>{w.skill} · {Math.round(w.score)}%</span>):<span>Complete more learning to build a mastery profile.</span>}</div><button className="danger" disabled={suggested<=0} onClick={()=>onDeduct(kid,suggested)}>Apply suggested deduction (${suggested.toFixed(2)})</button><div className="records">{wr.length===0?<p>No completed learning in this range.</p>:wr.slice(-12).reverse().map(r=><div key={r.id}><span>{r.subject} Quiz {r.quiz}</span><span>{Math.round(r.firstAttemptAccuracy*100)}%</span><span>{r.passedAllowanceRule?`+$${r.earned.toFixed(2)}`:'No allowance'}</span></div>)}</div><div className="admin-subsection"><strong>Active goals</strong>{p.goals.filter(g=>g.active).map(g=><p key={g.id}>🎯 {g.text} · Bonus ${g.reward.toFixed(2)}</p>)}</div><div className="admin-subsection"><strong>Recent parent notes</strong>{p.notes.slice(-2).map(n=><p key={n.id}>💬 {n.text}</p>)}</div></article>})}</section></main>
}
