import { useEffect, useMemo, useRef, useState } from 'react'
import type { AttemptResult, KidName, Question, Subject } from '../types'
import { remediationQuestion } from '../engine/quizEngine'
import { scoreResults, STREAK_BONUS } from '../engine/scoring'
import { primeVoices, speakText } from '../engine/voices'
import QuestionVisual from './QuestionVisual'

interface Props{kid:KidName;subject:Subject;quiz:number;questions:Question[];onFinish:(results:AttemptResult[],bonus:number,total:number)=>void;onExit:()=>void;voiceName?:string}
export default function QuizScreen({kid,subject,quiz,questions:initial,onFinish,onExit,voiceName}:Props){
 const [queue,setQueue]=useState<Question[]>(initial),[index,setIndex]=useState(0),[attempts,setAttempts]=useState(0),[disabled,setDisabled]=useState(false),[wrong,setWrong]=useState<string[]>([]),[feedback,setFeedback]=useState(''),[results,setResults]=useState<AttemptResult[]>([]),[streak,setStreak]=useState(0),[bonus,setBonus]=useState(0),[effect,setEffect]=useState<'none'|'correct'|'hint'>('none')
 const lastClick=useRef(0),q=queue[index],summary=useMemo(()=>scoreResults(results,bonus),[results,bonus])
 useEffect(()=>primeVoices(),[])
 const speak=(text:string)=>speakText(text,voiceName,(kid==='Humberto'||kid==='Harmoni') ? .82 : .9)
 useEffect(()=>{if(q){const timer=setTimeout(()=>speak(q.speak),180);return()=>clearTimeout(timer)}},[index,q?.id])
 if(!q)return <main className="page-shell"><section className="loading-card"><div className="loading-bubbles">🫧</div><p>Preparing lesson…</p></section></main>

 const complete=(eventually:boolean,attemptCount:number)=>{const first=eventually&&attemptCount===1,result={questionId:q.id,skill:q.skill,firstAttemptCorrect:first,eventuallyCorrect:eventually,attempts:attemptCount},nextResults=[...results,result];setResults(nextResults);let extra=0;if(first){setEffect('correct');const ns=streak+1;setStreak(ns);if(ns%3===0){extra=STREAK_BONUS;setBonus(b=>Number((b+extra).toFixed(2)));setFeedback('🔥 3-answer streak! +$0.05 bonus pending.')}else setFeedback('✅ First try! Great thinking!')}else setStreak(0);if(!eventually||attemptCount>1){const rem=remediationQuestion(q,nextResults.length);if(rem.id!==q.id)setQueue(prev=>{const at=Math.min(prev.length,index+4);return[...prev.slice(0,at),rem,...prev.slice(at)]})}setDisabled(true);setTimeout(()=>{setEffect('none');const next=index+1;if(next>=queue.length)onFinish(nextResults,bonus+extra,queue.length);else{setIndex(next);setAttempts(0);setWrong([]);setFeedback('');setDisabled(false)}},1450)}

 const choose=(choice:string)=>{if(disabled||wrong.includes(choice))return;const now=Date.now();if(now-lastClick.current<350){setDisabled(true);setEffect('hint');setFeedback('🧠 Think first. Choose when you’re ready.');setTimeout(()=>{setDisabled(false);setEffect('none')},1200);lastClick.current=now;return}lastClick.current=now;const a=attempts+1;setAttempts(a);if(choice===q.answer){complete(true,a);return}setWrong(w=>[...w,choice]);setStreak(0);setEffect('hint');if(a===1){setDisabled(true);setFeedback(`💡 ${q.hint}`);speak(q.hint);setTimeout(()=>{setDisabled(false);setEffect('none')},1550)}else{setFeedback(`The answer is ${q.answer}. ${q.hint}`);speak(`The answer is ${q.answer}. ${q.hint}`);complete(false,a)}}

 return <main className="quiz-shell"><div className="quiz-watermark" aria-hidden="true">🫧</div><header className="quiz-top"><button className="secondary" onClick={onExit}>Exit</button><div><strong>{kid} · {subject} · Quiz {quiz}</strong><span>Question {index+1} of {queue.length}</span></div><div className="accuracy-live">First-try: {results.length?Math.round(summary.accuracy*100):100}%</div></header><div className="progress"><div style={{width:`${((index+1)/queue.length)*100}%`}}/></div><section className={`question-card ${effect==='correct'?'correct-pop':''} ${effect==='hint'?'hint-pulse':''}`}><div className="question-number">#{index+1}</div><p className="skill-chip">{q.skill}</p><h1>{q.prompt}</h1><QuestionVisual q={q}/><button className="speak-btn" onClick={()=>speak(q.speak)}>🔊 Hear Question</button><div className="answer-grid">{q.choices.map(c=><button key={c} disabled={disabled||wrong.includes(c)} className={wrong.includes(c)?'wrong':''} onClick={()=>choose(c)}>{q.visual?.kind==='color'?<span className="answer-color" style={{background:c.toLowerCase()}}/>:subject==='DigitalTime'?<span className="mini-digital-clock">{c}</span>:c}</button>)}</div><div className="feedback" aria-live="polite">{feedback}</div><div className="session-line"><span>🔥 Streak: {streak}</span><span>Bonus pending: ${bonus.toFixed(2)}</span></div>{effect==='correct'&&<div className="celebration-burst" aria-hidden="true"><i>⭐</i><i>✨</i><i>⭐</i><i>✨</i><i>⭐</i></div>}</section></main>
}
