import {children} from '../data/children'
import {subjectMeta} from '../data/learningCatalog'
import {remainingWindowMs,subjectCompleted} from '../engine/storage'
import {quizCountFor} from '../engine/quizEngine'
import {masteryAverage,reviewDueSkills,weakestSkills} from '../engine/mastery'
import type {AppState,KidName,Subject} from '../types'
interface Props{state:AppState;kid:KidName;onSubject:(s:Subject)=>void;onHome:()=>void;onStore:()=>void;onOcean:()=>void}
const f=(ms:number)=>`${Math.floor(ms/3600000)}h ${Math.floor((ms%3600000)/60000)}m`,groups=['Daily','Math','Reading','Science','World Studies','Skills','Assessment'] as const
export default function SubjectScreen({state,kid,onSubject,onHome,onStore,onOcean}:Props){const cfg=children[kid],p=state.kids[kid],weak=weakestSkills(p.mastery,3),due=reviewDueSkills(p.mastery,99),required=['Math','DigitalTime','Science','Fractions','Geometry'].filter(s=>cfg.subjects.includes(s as Subject)) as Subject[],readingOnly=kid==='Harmoni'&&required.length>0&&required.every(s=>subjectCompleted(state,kid,s).length>=1);return <main className="page-shell game-learning-shell"><header className="page-header"><button className="secondary" onClick={onHome}>← Expedition</button><div><h1>{p.avatar} {kid}</h1><p>{cfg.grade} · Window reset in {f(remainingWindowMs(state,kid))}</p></div><div className="top-actions"><button className="secondary" onClick={onStore}>🛍️ Store</button></div></header><section className="stats-strip"><div><span>12-Hour Earnings</span><strong>${p.window.earnings.toFixed(2)}</strong></div><div><span>Total Bank</span><strong>${p.bank.toFixed(2)}</strong></div><div><span>Overall Mastery</span><strong>{Math.round(masteryAverage(p.mastery))}%</strong></div><div><span>Review Due</span><strong>{due.length}</strong></div><div><span>Adventure Energy</span><strong>⚡ {p.adventure.energy}/12</strong></div></section>{weak.length>0&&<section className="focus-banner"><strong>🎯 Current focus:</strong>{weak.map(w=><span key={w.skill}>{w.skill} · {Math.round(w.score)}%</span>)}</section>}{readingOnly&&<section className="reading-priority-banner"><div>📚</div><div><strong>Reading Priority Mode</strong><p>Harmoni completed her required non-reading learning for this window. Reading-focused activities remain available until reset.</p></div></section>}{groups.map(group=>{const subjects=cfg.subjects.filter(s=>subjectMeta[s].group===group);if(!subjects.length)return null;return <section className="subject-group" key={group}><h2>{group}</h2><div className="subject-grid">{subjects.map(subject=>{const meta=subjectMeta[subject],completed=subjectCompleted(state,kid,subject),count=quizCountFor(subject),reading=['Reading','SightWords','ReadingFluency','Phonics','LetterSounds','Rhyming','CVCWords','SpellingBee','DailyReview','WeakSkills','Vocabulary','SentenceBuilder','Grammar','Punctuation','Capitalization','ParagraphSequencing','MainIdea','Inference','CauseEffect','SequenceEvents','ContextClues'].includes(subject),locked=kid==='Harmoni'&&readingOnly&&!reading;return <button className={`subject-card ${locked?'locked':''}`} disabled={locked} onClick={()=>onSubject(subject)} key={subject}><span>{meta.icon}</span><h3>{meta.label}</h3><p>{locked?'Locked until reset. Reading remains available.':meta.description}</p><small>{count===1?`${completed.length}/1 completed`:`${completed.length}/${count} quizzes completed`}</small></button>})}</div></section>})}</main>}
