import fs from 'node:fs'
const required=['src/App.tsx','src/main.tsx','src/styles.css','src/data/questionFactory.ts','src/data/adventure.ts','src/data/worlds.ts','src/engine/quizEngine.ts','src/engine/validation.ts','src/engine/adventure.ts','src/engine/familyAchievements.ts','src/components/AdventureGame.tsx','src/components/AdventureHub.tsx','src/components/WorldMap.tsx','src/components/KnowledgeBank.tsx','src/components/Storefront.tsx','src/components/SkillTree.tsx','src/components/NetworkStatus.tsx','scripts/audit-questions.ts','scripts/content_audit.py','scripts/engine-tests.ts','public/sw.js','.github/workflows/deploy.yml','vite.config.ts']
const missing=required.filter(p=>!fs.existsSync(p));if(missing.length){console.error('Missing required v9 project files:',missing);process.exit(1)}
const vite=fs.readFileSync('vite.config.ts','utf8');if(!vite.includes("base: '/coleman-learning/'")){console.error('Vite base path must be /coleman-learning/');process.exit(1)}
const types=fs.readFileSync('src/types.ts','utf8');for(const token of ['SkillMastery','AdventureProgress','FamilyAchievement','KnowledgeCard','AllowanceRules','DailyChallenge','answerExposureAllowed','bossesDefeated'])if(!types.includes(token)){console.error('Missing v9 type:',token);process.exit(1)}
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));if(pkg.version!=='9.0.0'){console.error('Package version must be 9.0.0');process.exit(1)}if(!pkg.dependencies?.phaser){console.error('Phaser must be bundled as a project dependency');process.exit(1)}
const html=fs.readFileSync('index.html','utf8');if(/cdn\.jsdelivr\.net\/npm\/phaser/i.test(html)){console.error('Phaser must not depend on an external CDN');process.exit(1)}
const visual=fs.readFileSync('src/components/QuestionVisual.tsx','utf8');if(/numerator} of {v\.denominator}|equal parts shaded<\/small>/i.test(visual)){console.error('Fraction visual must not print numerator/denominator answer text.');process.exit(1)}
const adventure=fs.readFileSync('src/engine/adventure.ts','utf8');if(!adventure.includes('zoneExplorationComplete')||!adventure.includes('p.adventure.level<next.minLevel')){console.error('World 1 progression gate is missing.');process.exit(1)}
console.log('Coleman Learning v9 project structure verified.')
