import fs from 'node:fs'
const required=['src/App.tsx','src/main.tsx','src/styles.css','src/data/questionFactory.ts','src/data/adventure.ts','src/engine/quizEngine.ts','src/engine/validation.ts','src/engine/adventure.ts','src/engine/familyAchievements.ts','src/components/AdventureGame.tsx','src/components/HomeScreen.tsx','src/components/KnowledgeBank.tsx','src/components/Storefront.tsx','src/components/SkillTree.tsx','src/components/NetworkStatus.tsx','scripts/audit-questions.ts','scripts/content_audit.py','scripts/engine-tests.ts','public/sw.js','.github/workflows/deploy.yml','vite.config.ts']
const missing=required.filter(p=>!fs.existsSync(p));if(missing.length){console.error('Missing required v11 project files:',missing);process.exit(1)}
const vite=fs.readFileSync('vite.config.ts','utf8');if(!vite.includes("base: '/coleman-learning/'")){console.error('Vite base path must be /coleman-learning/');process.exit(1)}
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));if(pkg.version!=='11.0.0'){console.error('Package version must be 11.0.0');process.exit(1)}if(!pkg.dependencies?.phaser){console.error('Phaser must be bundled as a project dependency');process.exit(1)}
const html=fs.readFileSync('index.html','utf8');if(/cdn\.jsdelivr\.net\/npm\/phaser/i.test(html)){console.error('Phaser must not depend on an external CDN');process.exit(1)}
const app=fs.readFileSync('src/App.tsx','utf8');if(/AdventureHub|WorldMap|adventureHub|worldMap/.test(app)){console.error('v11 child flow must not expose the old Adventure Hub or World Map screens.');process.exit(1)}if(!app.includes("setScreen('adventureGame')")){console.error('v11 must route explorers directly into the HTML5 expedition.');process.exit(1)}
const home=fs.readFileSync('src/components/HomeScreen.tsx','utf8');if(!home.includes('ENTER EXPEDITION')||/World 2|World 3|World 4|locked worlds/i.test(home)){console.error('Explorer select must be game-first and must not show future worlds.');process.exit(1)}
const game=fs.readFileSync('src/components/AdventureGame.tsx','utf8');for(const token of ['expedition-v11','CURRENT MISSION','EXPLORE & DISCOVER','LEARN','AQUARIUM','JOURNAL'])if(!game.includes(token)){console.error('Missing v11 design-target game element:',token);process.exit(1)}
const visual=fs.readFileSync('src/components/QuestionVisual.tsx','utf8');if(/numerator} of {v\.denominator}|equal parts shaded<\/small>/i.test(visual)){console.error('Fraction visual must not print numerator/denominator answer text.');process.exit(1)}
const adventure=fs.readFileSync('src/engine/adventure.ts','utf8');if(!adventure.includes('zoneExplorationComplete')||!adventure.includes('p.adventure.level<next.minLevel')){console.error('World 1 progression gate is missing.');process.exit(1)}
console.log('Coleman Learning v11 design-target project structure verified.')
